import React, { useState, useEffect } from 'react';
import { Presentation, Loader2 } from 'lucide-react';
import { initAuth, googleSignIn, getAccessToken } from '../lib/auth';

interface ExportToSlidesProps {
  appliance: string;
  brand: string;
  guides: string[];
}

export function ExportToSlides({ appliance, brand, guides }: ExportToSlidesProps) {
  const [needsAuth, setNeedsAuth] = useState(false);
  const [token, setToken] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportUrl, setExportUrl] = useState<string | null>(null);

  useEffect(() => {
    const unsubscribe = initAuth(
      (user, t) => {
        setNeedsAuth(false);
        setToken(t);
      },
      () => setNeedsAuth(true)
    );
    return () => unsubscribe();
  }, []);

  const handleLogin = async () => {
    try {
      const result = await googleSignIn();
      if (result) {
        setToken(result.accessToken);
        setNeedsAuth(false);
      }
    } catch (err) {
      console.error('Login failed:', err);
    }
  };

  const handleExport = async () => {
    const currentToken = token || (await getAccessToken());
    if (!currentToken) {
      alert('Authentication required!');
      return;
    }
    
    // Add user confirmation before creating the presentation
    const confirmed = window.confirm(
      `Create a new Google Slides presentation with the repair guide for your ${brand} ${appliance}?`
    );
    if (!confirmed) return;
    
    setIsExporting(true);
    try {
      // 1. Create a new presentation
      const createRes = await fetch('https://slides.googleapis.com/v1/presentations', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${currentToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          title: `Diagnostic Report: ${brand} ${appliance}`
        })
      });
      
      const createData = await createRes.json();
      if (!createRes.ok) throw new Error(createData.error?.message || 'Failed to create presentation');
      
      const presentationId = createData.presentationId;

      // 2. Add content to existing title slide and create new slide for steps
      // Note: We'll do a simple batchUpdate
      const requests: any[] = [];
      const slides = createData.slides;
      
      if (slides && slides.length > 0) {
         const titleSlide = slides[0];
         const elements = titleSlide.pageElements;
         
         if (elements && elements.length >= 2) {
           requests.push({
             insertText: {
               objectId: elements[0].objectId,
               text: `Repair Guide\n${brand} ${appliance}`
             }
           });
           requests.push({
             insertText: {
               objectId: elements[1].objectId,
               text: 'Generated by FixItFelix'
             }
           });
         }
      }

      // Add a slide for the guides
      const newSlideId = 'guides_slide_1';
      requests.push({
        createSlide: {
          objectId: newSlideId,
          insertionIndex: 1,
          slideLayoutReference: { predefinedLayout: 'TITLE_AND_BODY' }
        }
      });
      
      // Update new slide text
      // We don't have the object IDs of the new slide out of the box unless we do a separate request,
      // but we can just use the response from createSlide if we split the batch.
      
      await fetch(`https://slides.googleapis.com/v1/presentations/${presentationId}:batchUpdate`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${currentToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ requests })
      });
      
      // Split batch update for the 2nd slide text insertion
      const updatedPresRes = await fetch(`https://slides.googleapis.com/v1/presentations/${presentationId}`, {
        headers: { 'Authorization': `Bearer ${currentToken}` }
      });
      const updatedPresData = await updatedPresRes.json();
      
      const secondSlide = updatedPresData.slides.find((s: any) => s.objectId === newSlideId);
      if (secondSlide) {
        const textElements = secondSlide.pageElements;
        const bodyRequests: any[] = [];
        if (textElements && textElements.length >= 2) {
           bodyRequests.push({
             insertText: {
               objectId: textElements[0].objectId,
               text: 'Troubleshooting Steps'
             }
           });
           bodyRequests.push({
             insertText: {
               objectId: textElements[1].objectId,
               text: guides.map((g, i) => `${i + 1}. ${g}`).join('\n')
             }
           });
        }
        
        await fetch(`https://slides.googleapis.com/v1/presentations/${presentationId}:batchUpdate`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${currentToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({ requests: bodyRequests })
        });
      }

      setExportUrl(`https://docs.google.com/presentation/d/${presentationId}/edit`);
      
    } catch (err: any) {
      console.error(err);
      alert('Error exporting to slides: ' + err.message);
    } finally {
      setIsExporting(false);
    }
  };

  if (exportUrl) {
    return (
      <div className="flex items-center justify-between p-4 bg-yellow-50 rounded-2xl border border-yellow-200 mt-4">
        <div className="flex items-center gap-3">
          <Presentation className="w-5 h-5 text-yellow-600" />
          <span className="font-medium text-yellow-900">Export Complete</span>
        </div>
        <a href={exportUrl} target="_blank" rel="noreferrer" className="text-sm font-semibold text-yellow-700 bg-yellow-100 hover:bg-yellow-200 px-4 py-2 rounded-full transition">
          Open Presentation
        </a>
      </div>
    );
  }

  return (
    <div className="mt-4 pt-4 border-t border-neutral-100">
      {needsAuth ? (
        <button
          onClick={handleLogin}
          className="w-full flex items-center justify-center gap-3 py-3 px-4 bg-white border border-neutral-200 rounded-full font-medium hover:bg-neutral-50 transition shadow-sm text-neutral-700"
        >
          <svg className="w-5 h-5" viewBox="0 0 48 48">
            <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/>
            <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"/>
            <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"/>
            <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"/>
          </svg>
          Sign in to Export to Google Slides
        </button>
      ) : (
        <button
          onClick={handleExport}
          disabled={isExporting}
          className="w-full flex items-center justify-center gap-2 py-3 px-4 bg-yellow-50 text-yellow-700 border border-yellow-200 rounded-full font-medium hover:bg-yellow-100 transition shadow-sm"
        >
          {isExporting ? <Loader2 className="w-5 h-5 animate-spin" /> : <Presentation className="w-5 h-5" />}
          {isExporting ? "Exporting..." : "Export to Google Slides"}
        </button>
      )}
    </div>
  );
}
